# Generated by Django 5.2.8 on 2025-11-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_convert_survey_type_to_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Mark this choice as the correct answer'),
        ),
    ]
