# Generated by Django 5.2.8 on 2025-11-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_choice_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='assigned_section',
        ),
        migrations.AddField(
            model_name='survey',
            name='assigned_sections',
            field=models.ManyToManyField(blank=True, help_text='Select one or more sections. Leave empty to assign to all sections.', related_name='surveys', to='my_app.section'),
        ),
    ]
